import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../scripts/staging/fixtures_v942.mjs', import.meta.url), 'utf8');
const catalogs = JSON.parse(readFileSync(new URL('../scripts/staging/catalogos_v942.json', import.meta.url), 'utf8'));

assert.match(source, /const EXPECTED_REF = 'odlwbuagtrgmfpdohors'/);
assert.match(source, /projectRef\(url\) !== EXPECTED_REF/);
assert.match(source, /CONFIRM_STAGING_PROJECT/);
assert.match(source, /--execute/);
assert.match(source, /--confirm-delete=STG942/);
assert.match(source, /STAGING_TEST_PASSWORD/);
assert.match(source, /SUPABASE_SECRET_KEY/);
assert.match(source, /SUPABASE_PUBLISHABLE_KEY/);
assert.match(source, /example\.invalid/);
assert.match(source, /app_metadata: \{ fixture: TAG \}/);
assert.doesNotMatch(source, /sb_secret_[A-Za-z0-9_-]+/);
assert.doesNotMatch(source, /service_role\s*[:=]\s*['"][^'"]+['"]/i);
assert.doesNotMatch(source, /jmcbaduxjrzfnesbslmp/);
assert.doesNotMatch(source, /delete\(\)\.neq\(/);
assert.doesNotMatch(source, /truncate\s+/i);
assert.doesNotMatch(source, /drop\s+(?:table|schema|database)/i);
assert.match(source, /like\('notas', `\[\$\{TAG\}\] escenario %`\)/);
assert.match(source, /like\('codigo_lote', `\$\{TAG\}-%`\)/);
assert.match(source, /email\?\.endsWith\(EMAIL_SUFFIX\)/);
assert.equal(catalogs.modulos_sistema.length, 22);
assert.equal(catalogs.roles_permisos.length, 224);
assert.equal(catalogs.orden_transiciones_v9382.length, 68);
const transitionKeys = catalogs.orden_transiciones_v9382.map((x) => JSON.stringify([x.estado_anterior, x.estado_nuevo]));
assert.equal(new Set(transitionKeys).size, transitionKeys.length);
assert.ok(source.includes("onConflict: 'estado_anterior,estado_nuevo'"));
assert.ok(!source.includes("onConflict: 'estado_anterior,estado_nuevo,modulo'"));
assert.ok(source.includes("auth.admin.updateUserById(user.id, { password })"));
const productStart = source.indexOf("const products = await checked(sb.from('productos_despacho').upsert([");
const productEnd = source.indexOf("], { onConflict: 'nombre' }).select", productStart);
assert.ok(productStart >= 0 && productEnd > productStart);
const productBatch = source.slice(productStart, productEnd);
assert.equal((productBatch.match(/tipo_despacho_peso:/g) ?? []).length, 3);
assert.equal((productBatch.match(/suma_peso_final:/g) ?? []).length, 3);
assert.ok(source.includes("tipo: 'Preparado'"));
assert.ok(!source.includes("tipo: 'Preparación'"));
assert.ok(source.includes("vendedorSb.rpc('guardar_orden_v9381'"));
assert.ok(!source.includes("from('ordenes').insert("));
assert.ok(!source.includes("userSb.from('orden_detalle').insert("));
assert.ok(source.includes("sessionByRole.get(roleByModule[modulo])"));
assert.ok(source.includes("p_cambios: { resultado_entrega: 'Entregado a crédito', monto_pendiente: 3450 }"));
assert.ok(source.includes("existingOrders.filter((o) => o.notas === orderRow.notas)"));
assert.ok(source.includes("canal: 'WhatsApp', prioridad: 'Normal'"));
assert.ok(source.includes("dateInTimeZone('America/Santo_Domingo')"));
assert.ok(source.includes("fecha: todayRD, fecha_despacho: todayRD"));
assert.ok(source.includes("p_orden_id: existing?.id ?? null"));
assert.ok(source.includes("if (existing) delete orderPayload.tomado_por_empleado_id"));
assert.ok(source.includes("p_orden: orderPayload"));
assert.ok(!source.includes("if (matches.length === 1) {"));
assert.ok(!source.includes("from('ordenes').delete("));
assert.ok(source.includes("rpc('cancelar_orden_v9383'"));
assert.ok(source.includes("detalles: 12, pesos: 4, facturas: 3, lotes: 1, detalle_lote: 1"));
assert.match(catalogs.source, /sin usuarios ni datos operativos/);

console.log('OK: paquete de fixtures V9.4.2 aislado, confirmable y sin credenciales.');
