begin;

-- =========================================================
-- V9.3.8.3 - CANCELACIÓN Y ARCHIVADO SEGURO DE ÓRDENES
-- Ejecutar una sola vez después del SQL 40.
-- No elimina órdenes, detalles, pesajes, pagos ni historiales.
-- =========================================================

alter table public.ordenes
  add column if not exists archivada boolean not null default false,
  add column if not exists archivada_en timestamptz,
  add column if not exists archivada_por uuid references auth.users(id),
  add column if not exists motivo_anulacion text;

create index if not exists idx_ordenes_archivada_estado
  on public.ordenes(archivada,estado,id desc);

create table if not exists public.orden_archivos_v9383(
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete restrict,
  orden_codigo text not null,
  accion text not null check(accion in('Anulada','Archivada')),
  motivo text not null check(char_length(btrim(motivo))>=5),
  estado_anterior text not null,
  usuario_id uuid not null references auth.users(id),
  creado_en timestamptz not null default now(),
  snapshot jsonb not null
);

create index if not exists idx_orden_archivos_v9383_orden
  on public.orden_archivos_v9383(orden_id,creado_en desc);

alter table public.orden_archivos_v9383 enable row level security;
drop policy if exists v9383_orden_archivos_admin_select on public.orden_archivos_v9383;
create policy v9383_orden_archivos_admin_select
on public.orden_archivos_v9383 for select to authenticated
using(public.es_admin_operativo());

revoke all on public.orden_archivos_v9383 from anon,authenticated;
grant select on public.orden_archivos_v9383 to authenticated;

create or replace function public.pc_bloquear_borrado_trazabilidad_v9383()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
begin
  raise exception 'El borrado físico está bloqueado. Utiliza Cancelar/Archivar para conservar la trazabilidad.';
end;
$$;

drop trigger if exists trg_bloquear_delete_orden_v9383 on public.ordenes;
create trigger trg_bloquear_delete_orden_v9383
before delete on public.ordenes for each row
execute function public.pc_bloquear_borrado_trazabilidad_v9383();

drop trigger if exists trg_bloquear_delete_historial_v9383 on public.orden_estados_historial;
create trigger trg_bloquear_delete_historial_v9383
before delete on public.orden_estados_historial for each row
execute function public.pc_bloquear_borrado_trazabilidad_v9383();

drop trigger if exists trg_bloquear_delete_archivo_v9383 on public.orden_archivos_v9383;
create trigger trg_bloquear_delete_archivo_v9383
before delete on public.orden_archivos_v9383 for each row
execute function public.pc_bloquear_borrado_trazabilidad_v9383();

revoke delete on public.ordenes from anon,authenticated;
revoke delete on public.orden_estados_historial from anon,authenticated;
revoke update,delete on public.orden_archivos_v9383 from anon,authenticated;

create or replace function public.cancelar_orden_v9383(
  p_orden_id bigint,
  p_estado_esperado text,
  p_motivo text,
  p_archivar boolean default false
) returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_o public.ordenes%rowtype;
  v_avanzada boolean:=false;
  v_snapshot jsonb;
  v_accion text;
  v_perfil public.perfiles%rowtype;
begin
  if v_uid is null then raise exception 'Sesión requerida.'; end if;
  if not public.es_admin_operativo() then
    raise exception 'Solo Gerente/Administrador puede cancelar o archivar órdenes.';
  end if;
  if char_length(btrim(coalesce(p_motivo,'')))<5 then
    raise exception 'El motivo debe tener al menos 5 caracteres.';
  end if;

  select * into v_o from public.ordenes where id=p_orden_id for update;
  if not found then raise exception 'La orden no existe.'; end if;
  if v_o.estado<>p_estado_esperado then
    raise exception 'La orden cambió de estado: se esperaba %, pero está en %.',p_estado_esperado,v_o.estado;
  end if;
  if v_o.estado='Anulado' or coalesce(v_o.archivada,false) then
    raise exception 'La orden ya está anulada o archivada.';
  end if;

  if exists(
    select 1 from public.entrega_lote_detalle d
    join public.entrega_lotes l on l.id=d.lote_id
    where d.orden_id=p_orden_id and coalesce(l.estado,'')<>'Revertido'
  ) then
    raise exception 'La orden pertenece a un lote activo. Corrige o revierte el lote antes de cancelarla.';
  end if;
  if exists(select 1 from public.orden_pagos where orden_id=p_orden_id)
     or exists(select 1 from public.orden_entregas where orden_id=p_orden_id) then
    raise exception 'La orden tiene entrega o pago registrado. Debe corregirse desde Liquidación antes de cancelarla.';
  end if;

  v_avanzada :=
    coalesce(v_o.estado,'') not in ('Programada','Pedido recibido')
    or v_o.tomado_por is not null
    or v_o.preparado_por is not null
    or v_o.facturado_por is not null
    or v_o.validado_por is not null
    or v_o.factura_no is not null
    or coalesce(v_o.cantidad_impresiones,0)>0
    or exists(select 1 from public.orden_pesos where orden_id=p_orden_id);

  if p_archivar and v_avanzada then
    raise exception 'Esta orden ya avanzó. Puede anularse, pero no ocultarse como una orden recién creada.';
  end if;

  select jsonb_build_object(
    'orden',to_jsonb(v_o),
    'detalle',coalesce((select jsonb_agg(to_jsonb(d) order by d.id) from public.orden_detalle d where d.orden_id=p_orden_id),'[]'::jsonb),
    'pesos',coalesce((select jsonb_agg(to_jsonb(p) order by p.id) from public.orden_pesos p where p.orden_id=p_orden_id),'[]'::jsonb),
    'entregas',coalesce((select jsonb_agg(to_jsonb(e) order by e.id) from public.orden_entregas e where e.orden_id=p_orden_id),'[]'::jsonb),
    'pagos',coalesce((select jsonb_agg(to_jsonb(pg) order by pg.id) from public.orden_pagos pg where pg.orden_id=p_orden_id),'[]'::jsonb)
  ) into v_snapshot;

  v_accion:=case when p_archivar then 'Archivada' else 'Anulada' end;

  update public.ordenes
  set estado='Anulado',
      archivada=p_archivar,
      archivada_en=case when p_archivar then now() else null end,
      archivada_por=case when p_archivar then v_uid else null end,
      motivo_anulacion=btrim(p_motivo),
      notas=concat_ws(E'\n',nullif(notas,''),'['||to_char(now(),'DD/MM/YYYY HH24:MI')||'] '||v_accion||': '||btrim(p_motivo)),
      actualizado_por=v_uid,
      actualizado_en=now()
  where id=p_orden_id;

  insert into public.orden_estados_historial(
    orden_id,estado_anterior,estado_nuevo,comentario,usuario
  ) values(
    p_orden_id,v_o.estado,'Anulado',v_accion||' de forma segura: '||btrim(p_motivo),v_uid
  );

  insert into public.orden_archivos_v9383(
    orden_id,orden_codigo,accion,motivo,estado_anterior,usuario_id,snapshot
  ) values(
    p_orden_id,v_o.codigo,v_accion,btrim(p_motivo),v_o.estado,v_uid,v_snapshot
  );

  select * into v_perfil from public.perfiles where id=v_uid;
  insert into public.auditoria_excepciones(
    usuario_id,usuario_nombre,usuario_rol,modulo,tipo_evento,gravedad,
    accion,motivo,orden_id,orden_codigo,cliente_nombre,detalle
  ) values(
    v_uid,coalesce(v_perfil.nombre,v_perfil.correo,v_uid::text),v_perfil.rol,
    'Órdenes','Cancelación segura de orden','Crítica',v_accion,btrim(p_motivo),
    p_orden_id,v_o.codigo,coalesce(v_o.cliente_nombre_orden,'Cliente'),
    jsonb_build_object('estado_anterior',v_o.estado,'archivada',p_archivar,'snapshot_id',
      currval(pg_get_serial_sequence('public.orden_archivos_v9383','id')))
  );

  return jsonb_build_object(
    'ok',true,'orden_id',p_orden_id,'codigo',v_o.codigo,
    'accion',v_accion,'estado','Anulado','archivada',p_archivar
  );
end;
$$;

revoke all on function public.cancelar_orden_v9383(bigint,text,text,boolean) from public,anon;
grant execute on function public.cancelar_orden_v9383(bigint,text,text,boolean) to authenticated;

-- Sustituye el reverso antiguo para que tampoco destruya órdenes ni historiales.
create or replace function public.revertir_gestion_segura(p_llamada_id bigint,p_motivo text)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_o public.ordenes%rowtype;
  v_total integer:=0;
  v_motivo text:=btrim(coalesce(p_motivo,''));
begin
  if v_uid is null then raise exception 'Sesión requerida.'; end if;
  if not public.es_admin_operativo() then raise exception 'Solo Gerente/Administrador puede revertir gestiones con órdenes.'; end if;
  if char_length(v_motivo)<5 then raise exception 'El motivo debe tener al menos 5 caracteres.'; end if;
  if not exists(select 1 from public.llamadas where id=p_llamada_id for update) then
    raise exception 'La gestión no existe o ya fue revertida.';
  end if;

  for v_o in select * from public.ordenes where llamada_id=p_llamada_id for update loop
    perform public.cancelar_orden_v9383(
      v_o.id,v_o.estado,'Reverso de gestión: '||v_motivo,
      v_o.estado in('Programada','Pedido recibido')
      and v_o.tomado_por is null and v_o.preparado_por is null
      and v_o.facturado_por is null and v_o.validado_por is null
      and not exists(select 1 from public.orden_pesos p where p.orden_id=v_o.id)
    );
    update public.ordenes
    set llamada_id=null,pedido_crm_id=null,actualizado_por=v_uid,actualizado_en=now()
    where id=v_o.id;
    v_total:=v_total+1;
  end loop;

  delete from public.pedidos where llamada_id=p_llamada_id;
  delete from public.llamadas where id=p_llamada_id;

  return jsonb_build_object(
    'ok',true,'message','Gestión revertida sin destruir órdenes ni trazabilidad.',
    'orders_archived_or_annulled',v_total
  );
end;
$$;

revoke all on function public.revertir_gestion_segura(bigint,text) from public,anon;
grant execute on function public.revertir_gestion_segura(bigint,text) to authenticated;

notify pgrst,'reload schema';
commit;
