begin;

-- =========================================================
-- V9.3.7.9 - AUDITORÍA PRIVADA DE EXCEPCIONES
-- Registra decisiones tomadas bajo responsabilidad.
-- Los empleados pueden registrar mediante RPC, pero solamente
-- Gerente/Administrador puede consultar y revisar.
-- =========================================================

create table if not exists public.auditoria_excepciones (
  id bigint generated by default as identity primary key,
  creado_en timestamptz not null default now(),
  usuario_id uuid not null,
  usuario_nombre text not null,
  usuario_rol text,
  empleado_id_texto text,
  empleado_nombre text,
  cuenta_estacion text,
  modulo text not null,
  tipo_evento text not null,
  gravedad text not null default 'Advertencia'
    check (gravedad in ('Informativa','Advertencia','Crítica')),
  accion text not null default 'Continuó bajo responsabilidad',
  motivo text not null check (char_length(btrim(motivo)) >= 5),
  orden_id bigint references public.ordenes(id) on delete set null,
  orden_codigo text,
  cliente_nombre text,
  lote_codigo text,
  valor_esperado numeric,
  valor_registrado numeric,
  diferencia numeric,
  tolerancia_aviso numeric,
  tolerancia_maxima numeric,
  unidad text,
  detalle jsonb not null default '{}'::jsonb,
  dispositivo text,
  estado_revision text not null default 'Pendiente'
    check (estado_revision in ('Pendiente','Revisado','Requiere seguimiento')),
  revisado_por uuid,
  revisado_en timestamptz,
  nota_administrativa text
);

create index if not exists idx_auditoria_excepciones_fecha
  on public.auditoria_excepciones(creado_en desc);
create index if not exists idx_auditoria_excepciones_revision
  on public.auditoria_excepciones(estado_revision, gravedad, creado_en desc);
create index if not exists idx_auditoria_excepciones_usuario
  on public.auditoria_excepciones(usuario_id, creado_en desc);
create index if not exists idx_auditoria_excepciones_orden
  on public.auditoria_excepciones(orden_id);

alter table public.auditoria_excepciones enable row level security;

drop policy if exists v9378_excepciones_admin_select on public.auditoria_excepciones;
create policy v9378_excepciones_admin_select
on public.auditoria_excepciones
for select to authenticated
using (public.es_admin_operativo());

revoke all on public.auditoria_excepciones from anon, authenticated;
grant select on public.auditoria_excepciones to authenticated;

create or replace function public.registrar_excepcion_v9378(p_evento jsonb)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_perfil public.perfiles%rowtype;
  v_id bigint;
  v_motivo text := btrim(coalesce(p_evento->>'motivo',''));
begin
  if v_uid is null then raise exception 'Sesión requerida'; end if;
  if char_length(v_motivo) < 5 then raise exception 'El motivo debe tener al menos 5 caracteres'; end if;

  select * into v_perfil from public.perfiles where id = v_uid;
  if coalesce(v_perfil.activo,false) is not true then raise exception 'Usuario inactivo'; end if;

  insert into public.auditoria_excepciones (
    usuario_id, usuario_nombre, usuario_rol, empleado_id_texto, empleado_nombre,
    cuenta_estacion, modulo, tipo_evento, gravedad, accion, motivo,
    orden_id, orden_codigo, cliente_nombre, lote_codigo,
    valor_esperado, valor_registrado, diferencia,
    tolerancia_aviso, tolerancia_maxima, unidad, detalle, dispositivo
  ) values (
    v_uid,
    coalesce(nullif(p_evento->>'usuario_nombre',''), v_perfil.nombre, v_perfil.correo, v_uid::text),
    v_perfil.rol,
    nullif(p_evento->>'empleado_id',''),
    nullif(p_evento->>'empleado_nombre',''),
    nullif(p_evento->>'cuenta_estacion',''),
    coalesce(nullif(p_evento->>'modulo',''),'Sistema'),
    coalesce(nullif(p_evento->>'tipo_evento',''),'Excepción operativa'),
    case when p_evento->>'gravedad' in ('Informativa','Advertencia','Crítica')
      then p_evento->>'gravedad' else 'Advertencia' end,
    coalesce(nullif(p_evento->>'accion',''),'Continuó bajo responsabilidad'),
    v_motivo,
    nullif(p_evento->>'orden_id','')::bigint,
    nullif(p_evento->>'orden_codigo',''),
    nullif(p_evento->>'cliente_nombre',''),
    nullif(p_evento->>'lote_codigo',''),
    nullif(p_evento->>'valor_esperado','')::numeric,
    nullif(p_evento->>'valor_registrado','')::numeric,
    nullif(p_evento->>'diferencia','')::numeric,
    nullif(p_evento->>'tolerancia_aviso','')::numeric,
    nullif(p_evento->>'tolerancia_maxima','')::numeric,
    nullif(p_evento->>'unidad',''),
    coalesce(p_evento->'detalle','{}'::jsonb),
    left(coalesce(p_evento->>'dispositivo',''),500)
  ) returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.revisar_excepcion_v9378(
  p_id bigint,
  p_estado text,
  p_nota text default null
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null or not public.es_admin_operativo() then
    raise exception 'Solo Gerente/Administrador puede revisar excepciones';
  end if;
  if p_estado not in ('Pendiente','Revisado','Requiere seguimiento') then
    raise exception 'Estado de revisión no válido';
  end if;

  update public.auditoria_excepciones
  set estado_revision = p_estado,
      nota_administrativa = nullif(btrim(coalesce(p_nota,'')),''),
      revisado_por = auth.uid(),
      revisado_en = now()
  where id = p_id;

  if not found then raise exception 'Excepción no encontrada'; end if;
end;
$$;

revoke all on function public.registrar_excepcion_v9378(jsonb) from public, anon;
grant execute on function public.registrar_excepcion_v9378(jsonb) to authenticated;
revoke all on function public.revisar_excepcion_v9378(bigint,text,text) from public, anon;
grant execute on function public.revisar_excepcion_v9378(bigint,text,text) to authenticated;

notify pgrst, 'reload schema';
commit;
