begin;

-- =========================================================
-- V9.3.9.2 · DEVOLUCIÓN PARCIAL POR ARTÍCULOS
-- Ejecutar una sola vez después del SQL 44.
-- Conserva la factura y el peso originales; registra cifras netas separadas.
-- =========================================================

alter table public.ordenes
  add column if not exists monto_devuelto numeric(14,2) not null default 0,
  add column if not exists peso_devuelto numeric(14,3) not null default 0,
  add column if not exists total_neto_liquidacion numeric(14,2),
  add column if not exists peso_neto_entregado numeric(14,3);

create table if not exists public.orden_devoluciones (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete restrict,
  monto_original numeric(14,2) not null,
  monto_devuelto numeric(14,2) not null check(monto_devuelto>0),
  monto_neto numeric(14,2) not null check(monto_neto>=0),
  peso_original numeric(14,3) not null default 0,
  peso_devuelto numeric(14,3) not null default 0 check(peso_devuelto>=0),
  peso_neto numeric(14,3) not null default 0 check(peso_neto>=0),
  estado text not null default 'Confirmada' check(estado in('Confirmada','Anulada')),
  observacion text,
  recibido_por text not null,
  creado_por uuid not null references auth.users(id),
  creado_en timestamptz not null default now()
);

create unique index if not exists uq_devolucion_activa_orden_v9392
  on public.orden_devoluciones(orden_id) where estado='Confirmada';

create table if not exists public.orden_devolucion_detalle (
  id bigint generated by default as identity primary key,
  devolucion_id bigint not null references public.orden_devoluciones(id) on delete restrict,
  orden_detalle_id bigint not null references public.orden_detalle(id) on delete restrict,
  producto_id bigint,
  producto_nombre text not null,
  unidad text,
  cantidad_entregada numeric(14,3) not null,
  cantidad_devuelta numeric(14,3) not null check(cantidad_devuelta>0),
  precio numeric(14,4) not null check(precio>=0),
  monto_devuelto numeric(14,2) not null check(monto_devuelto>=0),
  peso_devuelto numeric(14,3) not null default 0 check(peso_devuelto>=0),
  destino text not null check(destino in('Inventario','Merma','Revision')),
  motivo text not null check(length(btrim(motivo))>=3),
  unique(devolucion_id,orden_detalle_id)
);

create index if not exists idx_devoluciones_orden_v9392
  on public.orden_devoluciones(orden_id,creado_en desc);

alter table public.orden_devoluciones enable row level security;
alter table public.orden_devolucion_detalle enable row level security;

drop policy if exists devoluciones_select_v9392 on public.orden_devoluciones;
create policy devoluciones_select_v9392 on public.orden_devoluciones
for select to authenticated using (
  public.tiene_algun_modulo(array['liquidacion','ordenes','auditoria'],'ver')
  or public.es_admin_operativo()
);
drop policy if exists devolucion_detalle_select_v9392 on public.orden_devolucion_detalle;
create policy devolucion_detalle_select_v9392 on public.orden_devolucion_detalle
for select to authenticated using (
  exists(
    select 1 from public.orden_devoluciones d
    where d.id=devolucion_id and (
      public.tiene_algun_modulo(array['liquidacion','ordenes','auditoria'],'ver')
      or public.es_admin_operativo()
    )
  )
);

create or replace function public.registrar_devolucion_parcial_v9392(
  p_orden_id bigint,
  p_lineas jsonb,
  p_monto_recibido numeric,
  p_metodo text,
  p_recibido_por text,
  p_observacion text default null
) returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_orden public.ordenes%rowtype;
  v_lote public.entrega_lotes%rowtype;
  v_linea jsonb;
  v_det public.orden_detalle%rowtype;
  v_devolucion_id bigint;
  v_total numeric(14,2);
  v_devuelto numeric(14,2):=0;
  v_neto numeric(14,2);
  v_cash numeric(14,2):=round(coalesce(p_monto_recibido,0),2);
  v_peso_original numeric(14,3);
  v_peso_devuelto numeric(14,3):=0;
  v_peso_neto numeric(14,3);
  v_qty numeric(14,3);
  v_weight numeric(14,3);
  v_delivered numeric(14,3);
  v_amount numeric(14,2);
  v_final jsonb;
begin
  if v_uid is null then raise exception 'Sesión no válida.'; end if;
  if not public.puede_modulo_v930r5('liquidacion','editar') then
    raise exception 'No tienes permiso para recibir devoluciones.';
  end if;
  if jsonb_typeof(p_lineas)<>'array' or jsonb_array_length(p_lineas)=0 then
    raise exception 'Selecciona al menos un artículo devuelto.';
  end if;

  select * into v_orden from public.ordenes where id=p_orden_id for update;
  if not found then raise exception 'No se encontró la orden.'; end if;
  if v_orden.recibido_en is not null then raise exception 'Esta orden ya fue recibida por CXC.'; end if;
  if exists(select 1 from public.orden_devoluciones where orden_id=p_orden_id and estado='Confirmada') then
    raise exception 'Esta orden ya tiene una devolución parcial confirmada.';
  end if;

  select l.* into v_lote
  from public.entrega_lote_detalle d
  join public.entrega_lotes l on l.id=d.lote_id
  where d.orden_id=p_orden_id and lower(coalesce(l.estado,''))<>'revertido'
  order by l.id desc limit 1 for update of l;
  if not found then raise exception 'La orden no tiene un lote de delivery activo.'; end if;
  if lower(coalesce(v_lote.estado,''))='cerrado' then raise exception 'El lote ya está cerrado.'; end if;

  v_total:=round(coalesce(v_orden.total_factura,v_orden.total_estimado,0),2);
  v_peso_original:=round(coalesce(v_orden.peso_validado,v_orden.peso_preparado,0),3);

  for v_linea in select value from jsonb_array_elements(p_lineas)
  loop
    select * into v_det from public.orden_detalle
    where id=nullif(v_linea->>'detalle_id','')::bigint and orden_id=p_orden_id
    for update;
    if not found then raise exception 'Uno de los artículos no pertenece a la orden.'; end if;
    v_delivered:=coalesce(v_det.cantidad_preparada,v_det.cantidad_pedida,0);
    v_qty:=round(coalesce(nullif(v_linea->>'cantidad','')::numeric,0),3);
    v_weight:=round(coalesce(nullif(v_linea->>'peso','')::numeric,0),3);
    if v_qty<=0 or v_qty>v_delivered then
      raise exception 'Cantidad devuelta inválida para %.',v_det.producto_nombre;
    end if;
    if v_weight<0 or (v_peso_original>0 and v_peso_devuelto+v_weight>v_peso_original+0.001) then
      raise exception 'Peso devuelto inválido para %.',v_det.producto_nombre;
    end if;
    if coalesce(length(btrim(v_linea->>'motivo')),0)<3 then
      raise exception 'Escribe el motivo de devolución para %.',v_det.producto_nombre;
    end if;
    if coalesce(v_linea->>'destino','') not in('Inventario','Merma','Revision') then
      raise exception 'Destino de devolución inválido.';
    end if;
    v_amount:=round(v_qty*coalesce(v_det.precio,0),2);
    v_devuelto:=v_devuelto+v_amount;
    v_peso_devuelto:=v_peso_devuelto+v_weight;
  end loop;

  v_devuelto:=round(v_devuelto,2);
  v_peso_devuelto:=round(v_peso_devuelto,3);
  if v_devuelto<=0 then raise exception 'El valor devuelto debe ser mayor que cero.'; end if;
  if v_devuelto>=v_total-0.01 then raise exception 'La devolución total debe registrarse como No entregado.'; end if;
  v_neto:=round(v_total-v_devuelto,2);
  v_peso_neto:=greatest(round(v_peso_original-v_peso_devuelto,3),0);
  if abs(v_cash-v_neto)>0.01 then
    raise exception 'El efectivo debe coincidir con el total neto de %.',v_neto;
  end if;

  insert into public.orden_devoluciones(
    orden_id,monto_original,monto_devuelto,monto_neto,peso_original,peso_devuelto,
    peso_neto,observacion,recibido_por,creado_por
  ) values (
    p_orden_id,v_total,v_devuelto,v_neto,v_peso_original,v_peso_devuelto,
    v_peso_neto,nullif(btrim(p_observacion),''),coalesce(nullif(btrim(p_recibido_por),''),'CXC'),v_uid
  ) returning id into v_devolucion_id;

  for v_linea in select value from jsonb_array_elements(p_lineas)
  loop
    select * into v_det from public.orden_detalle
    where id=(v_linea->>'detalle_id')::bigint and orden_id=p_orden_id;
    v_delivered:=coalesce(v_det.cantidad_preparada,v_det.cantidad_pedida,0);
    v_qty:=round((v_linea->>'cantidad')::numeric,3);
    v_weight:=round(coalesce(nullif(v_linea->>'peso','')::numeric,0),3);
    v_amount:=round(v_qty*coalesce(v_det.precio,0),2);
    insert into public.orden_devolucion_detalle(
      devolucion_id,orden_detalle_id,producto_id,producto_nombre,unidad,
      cantidad_entregada,cantidad_devuelta,precio,monto_devuelto,peso_devuelto,destino,motivo
    ) values (
      v_devolucion_id,v_det.id,v_det.producto_id,v_det.producto_nombre,v_det.unidad,
      v_delivered,v_qty,coalesce(v_det.precio,0),v_amount,v_weight,
      v_linea->>'destino',btrim(v_linea->>'motivo')
    );
  end loop;

  if v_cash>0.01 then
    insert into public.orden_pagos(orden_id,cliente_id,monto,metodo,recibido_por)
    values(p_orden_id,v_orden.cliente_id,v_cash,coalesce(nullif(btrim(p_metodo),''),'Efectivo'),v_uid);
  end if;
  insert into public.orden_entregas(orden_id,resultado,monto_cobrado,monto_pendiente,notas,creado_por)
  values(p_orden_id,'Devuelto parcial',v_cash,v_devuelto,
    concat_ws(' | ',nullif(btrim(p_observacion),''),'Devolución V9.3.9.2 por artículos. Valor devuelto: '||v_devuelto||'. Total neto: '||v_neto||'.'),v_uid);

  update public.ordenes set
    estado='Devuelto parcial',resultado_entrega='Devuelto parcial',
    monto_cobrado=v_cash,monto_pendiente=v_devuelto,monto_devuelto=v_devuelto,
    total_neto_liquidacion=v_neto,peso_devuelto=v_peso_devuelto,peso_neto_entregado=v_peso_neto,
    recibido_por=coalesce(nullif(btrim(p_recibido_por),''),'CXC'),recibido_en=now(),
    notas_liquidacion=concat_ws(' | ',nullif(btrim(notas_liquidacion),''),
      nullif(btrim(p_observacion),''),'V9.3.9.2: devolución por artículos. Neto '||v_neto||'. Peso neto '||v_peso_neto||' lb.')
  where id=p_orden_id;

  update public.entrega_lote_detalle set
    estado_liquidacion='Recibido',resultado_entrega='Devuelto parcial',
    monto_cobrado=v_cash,monto_credito=0,
    monto_factura=v_neto,peso_entregado=v_peso_neto,
    observacion=concat_ws(' | ',nullif(btrim(observacion),''),'Devolución '||v_devuelto||' · peso devuelto '||v_peso_devuelto||' lb')
  where lote_id=v_lote.id and orden_id=p_orden_id;

  insert into public.orden_estados_historial(orden_id,estado_anterior,estado_nuevo,comentario,usuario)
  values(p_orden_id,v_orden.estado,'Devuelto parcial',
    'Devolución parcial V9.3.9.2. Factura original '||v_total||', devolución '||v_devuelto||', neto '||v_neto||', peso devuelto '||v_peso_devuelto||' lb.',v_uid);

  v_final:=public.pc_finalizar_lote_cxc_v937(v_lote.id,p_recibido_por,p_observacion);
  return v_final||jsonb_build_object(
    'orden_id',p_orden_id,'devolucion_id',v_devolucion_id,'resultado','Devuelto parcial',
    'monto_original',v_total,'monto_devuelto',v_devuelto,'monto_neto',v_neto,
    'peso_original',v_peso_original,'peso_devuelto',v_peso_devuelto,'peso_neto',v_peso_neto
  );
end;
$$;

revoke execute on function public.registrar_devolucion_parcial_v9392(bigint,jsonb,numeric,text,text,text) from public;
grant execute on function public.registrar_devolucion_parcial_v9392(bigint,jsonb,numeric,text,text,text) to authenticated;

notify pgrst,'reload schema';
commit;

select
  to_regclass('public.orden_devoluciones') is not null as devoluciones,
  to_regclass('public.orden_devolucion_detalle') is not null as detalle,
  to_regprocedure('public.registrar_devolucion_parcial_v9392(bigint,jsonb,numeric,text,text,text)') is not null as rpc;
