begin;

-- =========================================================
-- V9.3.9.0 - CONFIGURACIÓN GLOBAL Y CONTROL DE CONCURRENCIA
-- Ejecutar una sola vez después del SQL 42.
-- No elimina ni reinicia datos existentes.
-- =========================================================

alter table public.sistema_configuracion
  add column if not exists revision bigint not null default 1;

create table if not exists public.sistema_configuracion_historial_v9390(
  id bigint generated by default as identity primary key,
  clave text not null,
  valor_anterior jsonb,
  valor_nuevo jsonb not null,
  revision_anterior bigint,
  revision_nueva bigint not null,
  usuario_id uuid not null references auth.users(id),
  creado_en timestamptz not null default now()
);

create index if not exists idx_config_historial_v9390_clave_fecha
  on public.sistema_configuracion_historial_v9390(clave,creado_en desc);

alter table public.sistema_configuracion_historial_v9390 enable row level security;

drop policy if exists config_historial_v9390_admin_select
  on public.sistema_configuracion_historial_v9390;
create policy config_historial_v9390_admin_select
  on public.sistema_configuracion_historial_v9390
  for select to authenticated
  using(public.es_admin_operativo());

revoke all on public.sistema_configuracion_historial_v9390 from anon,authenticated;
grant select on public.sistema_configuracion_historial_v9390 to authenticated;

create or replace function public.guardar_configuracion_v9390(
  p_clave text,
  p_valor jsonb
) returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_actual public.sistema_configuracion%rowtype;
  v_revision bigint;
begin
  if v_uid is null then raise exception 'Sesión requerida.'; end if;
  if not public.es_admin_operativo() then
    raise exception 'Solo administración puede modificar la configuración global.';
  end if;
  if nullif(btrim(coalesce(p_clave,'')),'') is null then
    raise exception 'La clave de configuración es obligatoria.';
  end if;
  if p_valor is null then raise exception 'El valor de configuración es obligatorio.'; end if;

  select * into v_actual
  from public.sistema_configuracion
  where clave=p_clave
  for update;

  if found then
    v_revision:=coalesce(v_actual.revision,1)+1;
    update public.sistema_configuracion
       set valor=p_valor,
           actualizado_por=v_uid,
           actualizado_en=now(),
           revision=v_revision
     where clave=p_clave;
  else
    v_revision:=1;
    insert into public.sistema_configuracion(
      clave,valor,actualizado_por,actualizado_en,revision
    ) values(
      p_clave,p_valor,v_uid,now(),v_revision
    );
  end if;

  insert into public.sistema_configuracion_historial_v9390(
    clave,valor_anterior,valor_nuevo,revision_anterior,revision_nueva,usuario_id
  ) values(
    p_clave,
    case when v_actual.clave is null then null else v_actual.valor end,
    p_valor,
    case when v_actual.clave is null then null else v_actual.revision end,
    v_revision,
    v_uid
  );

  return jsonb_build_object(
    'ok',true,'clave',p_clave,'revision',v_revision,'actualizado_en',now()
  );
end;
$$;

revoke all on function public.guardar_configuracion_v9390(text,jsonb)
  from public,anon;
grant execute on function public.guardar_configuracion_v9390(text,jsonb)
  to authenticated;

create index if not exists idx_sistema_configuracion_revision_v9390
  on public.sistema_configuracion(revision desc,clave);

notify pgrst,'reload schema';
commit;
