-- =========================================================
-- V9.4.5 R1 · DESGLOSE DE EFECTIVO EN LIQUIDACIÓN
-- Conteo físico por lote, conciliado y guardado en la misma
-- transacción que cierra la recepción en CXC.
-- =========================================================
begin;

create table if not exists public.liquidacion_efectivo_conteos_v945 (
  id bigint generated by default as identity primary key,
  liquidacion_id bigint references public.liquidaciones_lotes(id) on delete set null,
  lote_id bigint references public.entrega_lotes(id) on delete set null,
  codigo_lote text not null,
  efectivo_esperado numeric(14,2) not null,
  efectivo_contado numeric(14,2) not null,
  ajuste_fraccion numeric(14,2) not null default 0,
  efectivo_conciliado numeric(14,2) generated always as (efectivo_contado + ajuste_fraccion) stored,
  diferencia numeric(14,2) not null default 0,
  desglose jsonb not null,
  motivo_ajuste text,
  recibido_por text,
  creado_por uuid references auth.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  constraint liquidacion_efectivo_conteos_v945_liquidacion_uq unique(liquidacion_id),
  constraint liquidacion_efectivo_conteos_v945_expected_ck check(efectivo_esperado>=0),
  constraint liquidacion_efectivo_conteos_v945_counted_ck check(efectivo_contado>=0),
  constraint liquidacion_efectivo_conteos_v945_adjustment_ck check(abs(ajuste_fraccion)<1),
  constraint liquidacion_efectivo_conteos_v945_json_ck check(jsonb_typeof(desglose)='array')
);

create index if not exists idx_liquidacion_efectivo_conteos_v945_lote
  on public.liquidacion_efectivo_conteos_v945(lote_id,creado_en desc);

alter table public.liquidacion_efectivo_conteos_v945 enable row level security;

drop policy if exists liquidacion_efectivo_conteos_v945_select on public.liquidacion_efectivo_conteos_v945;
create policy liquidacion_efectivo_conteos_v945_select
on public.liquidacion_efectivo_conteos_v945
for select to authenticated
using(public.puede_modulo_v930r5('liquidacion','ver'));

revoke all on table public.liquidacion_efectivo_conteos_v945 from public,anon,authenticated;
grant select on table public.liquidacion_efectivo_conteos_v945 to authenticated;

create or replace function public.recibir_lote_cxc_v945(
  p_lote_id bigint,
  p_items jsonb,
  p_desglose jsonb,
  p_ajuste_fraccion numeric,
  p_recibido_por text,
  p_observacion text default null
) returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_result jsonb;
  v_liquidacion_id bigint;
  v_codigo_lote text;
  v_esperado numeric(14,2);
  v_contado numeric(14,2);
  v_ajuste numeric(14,2):=round(coalesce(p_ajuste_fraccion,0),2);
  v_ajuste_esperado numeric(14,2);
  v_conciliado numeric(14,2);
  v_diferencia numeric(14,2);
  v_desglose_normalizado jsonb;
begin
  if auth.uid() is null then raise exception 'Sesión no válida.'; end if;
  if not public.puede_modulo_v930r5('liquidacion','editar') then
    raise exception 'No tienes permiso para recibir liquidaciones.';
  end if;
  if jsonb_typeof(p_desglose)<>'array' or jsonb_array_length(p_desglose)<>10 then
    raise exception 'El desglose debe incluir exactamente las diez denominaciones de caja.';
  end if;
  if exists(
    select 1 from jsonb_array_elements(p_desglose) j
    where case when coalesce(j->>'denominacion','')~'^[0-9]+$'
      then (j->>'denominacion')::integer else null end is null
      or case when coalesce(j->>'denominacion','')~'^[0-9]+$'
        then (j->>'denominacion')::integer else null end
        not in(2000,1000,500,200,100,50,25,10,5,1)
      or case when coalesce(j->>'cantidad','')~'^[0-9]+$'
        then (j->>'cantidad')::integer else null end is null
  ) then
    raise exception 'El desglose contiene denominaciones o cantidades inválidas.';
  end if;
  if (select count(distinct (j->>'denominacion')::integer) from jsonb_array_elements(p_desglose) j)<>10 then
    raise exception 'El desglose contiene una denominación repetida o ausente.';
  end if;
  if abs(v_ajuste)>=1 then
    raise exception 'El ajuste de fracción debe ser menor de RD$1.';
  end if;

  -- La función vigente conserva todas las validaciones de clientes, devoluciones,
  -- permisos y cierre. Cualquier error posterior revierte también estas escrituras.
  v_result:=public.recibir_lote_cxc_v9393(
    p_lote_id,p_items,p_recibido_por,p_observacion
  );
  v_liquidacion_id:=nullif(v_result->>'liquidacion_id','')::bigint;
  if coalesce((v_result->>'lote_cerrado')::boolean,false) is not true or v_liquidacion_id is null then
    raise exception 'El lote no alcanzó un cierre formal; no se guardó el conteo de efectivo.';
  end if;

  select codigo_lote,round(efectivo_recibido,2)
  into v_codigo_lote,v_esperado
  from public.liquidaciones_lotes
  where id=v_liquidacion_id
  for update;
  if not found then raise exception 'No se encontró la liquidación formal del lote.'; end if;

  select
    coalesce(sum(x.denominacion*x.cantidad),0)::numeric(14,2),
    jsonb_agg(jsonb_build_object(
      'denominacion',x.denominacion,
      'cantidad',x.cantidad,
      'subtotal',x.denominacion*x.cantidad
    ) order by x.denominacion desc)
  into v_contado,v_desglose_normalizado
  from (
    select (j->>'denominacion')::integer denominacion,
           (j->>'cantidad')::integer cantidad
    from jsonb_array_elements(p_desglose) j
  ) x;

  -- Las denominaciones son pesos enteros. La única conciliación admitida es
  -- el redondeo comercial determinista del esperado (0.50 redondea arriba).
  v_ajuste_esperado:=round(v_esperado-round(v_esperado,0),2);
  if v_contado<>round(v_esperado,0) then
    raise exception 'El efectivo físico no cuadra. Esperado: %, efectivo entero requerido: %, contado: %.',
      v_esperado,round(v_esperado,0),v_contado;
  end if;
  if abs(v_ajuste-v_ajuste_esperado)>0.009 then
    raise exception 'El ajuste de fracción no corresponde al redondeo requerido. Esperado: %, recibido: %.',
      v_ajuste_esperado,v_ajuste;
  end if;

  v_conciliado:=round(v_contado+v_ajuste,2);
  v_diferencia:=round(v_conciliado-v_esperado,2);
  if abs(v_diferencia)>0.009 then
    raise exception 'El efectivo físico no cuadra. Esperado: %, contado: %, ajuste: %, diferencia: %.',
      v_esperado,v_contado,v_ajuste,v_diferencia;
  end if;

  insert into public.liquidacion_efectivo_conteos_v945(
    liquidacion_id,lote_id,codigo_lote,efectivo_esperado,efectivo_contado,
    ajuste_fraccion,diferencia,desglose,motivo_ajuste,recibido_por,creado_por
  ) values (
    v_liquidacion_id,p_lote_id,v_codigo_lote,v_esperado,v_contado,
    v_ajuste,v_diferencia,v_desglose_normalizado,
    case when abs(v_ajuste)>0.009 then 'Ajuste automático por fracción menor de RD$1 no representable con las denominaciones configuradas.' end,
    nullif(btrim(p_recibido_por),''),auth.uid()
  );

  update public.liquidaciones_lotes
  set diferencia=v_diferencia
  where id=v_liquidacion_id;

  insert into public.liquidacion_lote_eventos(
    lote_id,codigo_lote,liquidacion_id,accion,motivo,
    usuario_id,usuario_nombre,metadata
  ) values (
    p_lote_id,v_codigo_lote,v_liquidacion_id,'efectivo_desglosado',
    case when abs(v_ajuste)>0.009 then 'Conciliación con ajuste de fracción.' else 'Conteo físico exacto.' end,
    auth.uid(),nullif(btrim(p_recibido_por),''),
    jsonb_build_object('version','9.4.5','efectivo_esperado',v_esperado,
      'efectivo_contado',v_contado,'ajuste_fraccion',v_ajuste,
      'efectivo_conciliado',v_conciliado,'diferencia',v_diferencia,
      'desglose',v_desglose_normalizado)
  );

  return v_result||jsonb_build_object(
    'version_desglose','9.4.5','efectivo_esperado',v_esperado,
    'efectivo_contado',v_contado,'ajuste_fraccion',v_ajuste,
    'efectivo_conciliado',v_conciliado,'diferencia',v_diferencia,
    'desglose',v_desglose_normalizado
  );
end;
$$;

revoke execute on function public.recibir_lote_cxc_v945(bigint,jsonb,jsonb,numeric,text,text)
  from public,anon;
grant execute on function public.recibir_lote_cxc_v945(bigint,jsonb,jsonb,numeric,text,text)
  to authenticated;

notify pgrst,'reload schema';
commit;

select
  to_regclass('public.liquidacion_efectivo_conteos_v945') is not null as tabla_conteo,
  to_regprocedure('public.recibir_lote_cxc_v945(bigint,jsonb,jsonb,numeric,text,text)') is not null as rpc_conteo;
