import fs from 'node:fs';
const main=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../src/styles.css',import.meta.url),'utf8');
const ok=(cond,msg)=>{ if(!cond){ console.error('ERROR - '+msg); process.exitCode=1; } else console.log('OK - '+msg); };
ok(main.includes('V9.3.0 R8') || main.includes('V9.3.0 R9'),'marcador R8/R9 visible');
ok(main.includes('prep-row-r8') && main.includes('prep-compact-grid'),'fila compacta de preparación');
ok(main.includes('<span>Solicitado</span>') && main.includes('<span>Preparado</span>') && main.includes('<span>Estado</span>'),'solicitado, preparado y estado en la misma fila');
ok(main.includes('itemInstruction(i)') && main.includes('prep-item-note'),'observación breve por artículo');
ok(main.includes('id="newItemNote"') && main.includes('data-row-note'),'captura y edición de corte por artículo');
ok(main.includes("notas:itemInstruction(it)"),'observación se conserva en orden_detalle.notas');
ok(!/prepRowsHtml[\s\S]{0,6000}Producto por libra: lo preparado equivale/.test(main),'texto repetitivo eliminado del bloque compacto');
ok(!/prepRowsHtml[\s\S]{0,6000}solicitado por el cliente/.test(main),'etiqueta repetitiva eliminada');
ok(main.includes('↳ ${instruction}'),'WhatsApp incluye instrucción sin precios');
ok(css.includes('V9.3.0 R8 — DESPACHO COMPACTO PARA TABLET'),'estilos R8 incluidos');
ok(css.includes('@media(max-width:940px)') && css.includes('.prep-modal-card-r8'),'optimización específica para tablet');
if(process.exitCode) process.exit(process.exitCode);
console.log('Auditoría Despacho Compacto V9.3.0 R8 aprobada.');
